CREATE TABLE referral (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code VARCHAR(255) NOT NULL,
  consumed BOOLEAN,
  app_user_id INTEGER,
  CONSTRAINT pk_referral PRIMARY KEY (id)
);

CREATE TABLE app_user (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255),
  my_referral_id INTEGER,
  credit INTEGER,
  CONSTRAINT pk_app_user PRIMARY KEY (id)
);

ALTER TABLE referral ADD CONSTRAINT uc_referral_code UNIQUE (code);

ALTER TABLE app_user ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE referral ADD CONSTRAINT FK_REFERRAL_ON_USER FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE app_user ADD CONSTRAINT FK_USER_ON_MY_REFERRAL FOREIGN KEY (my_referral_id) REFERENCES referral (id);